<?php
require_once __DIR__.'/../includes/header.php';require_once __DIR__.'/../config/database.php';check_access([2]);$db=Database::getInstance();
$pid=(int)($_GET['pengajaran_id']??0);$sid=(int)($_GET['siswa_id']??0);
$stmt=$db->prepare('SELECT p.id,p.kkm,p.kelas_id,p.semester,p.tahun_ajaran,m.nama_mapel,k.nama_kelas,g.id guru_id,g.nama_lengkap nama_guru,s.nisn,s.nama_lengkap FROM pengajaran p JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id JOIN guru g ON g.id=p.guru_id JOIN siswa s ON s.kelas_id=p.kelas_id WHERE p.id=? AND s.id=? AND g.user_id=?');$stmt->execute([$pid,$sid,$_SESSION['user_id']]);$info=$stmt->fetch();if(!$info){http_response_code(403);exit('Laporan tidak dapat diakses.');}
$stmt=$db->prepare('SELECT id,nama_komponen,bobot FROM komponen_penilaian WHERE pengajaran_id=? ORDER BY urutan,id');$stmt->execute([$pid]);$components=$stmt->fetchAll();
$stmt=$db->prepare("SELECT
 COALESCE((SELECT AVG(COALESCE(nu.nilai_total,0)) FROM ujian u LEFT JOIN nilai_ujian nu ON nu.ujian_id=u.id AND nu.siswa_id=? WHERE u.pengajaran_id=? AND u.jenis_ujian='Kuis' AND u.waktu_selesai<=NOW()),0) nilai_ulangan,
 COALESCE((SELECT AVG(COALESCE(pt.nilai,0)) FROM tugas t LEFT JOIN pengumpulan_tugas pt ON pt.tugas_id=t.id AND pt.siswa_id=? WHERE t.pengajaran_id=? AND t.deadline<=NOW()),0) nilai_tugas,
 COALESCE((SELECT AVG(CASE WHEN da.status IN ('Hadir','Sakit','Izin') THEN 100 ELSE 0 END) FROM sesi_absensi sa LEFT JOIN detail_absensi da ON da.sesi_absensi_id=sa.id AND da.siswa_id=? WHERE sa.pengajaran_id=? AND sa.status='Ditutup'),0) nilai_kehadiran");
$stmt->execute([$sid,$pid,$sid,$pid,$sid,$pid]);$auto=$stmt->fetch();
$stmt=$db->prepare('SELECT nk.komponen_id,nk.nilai FROM nilai_komponen nk JOIN komponen_penilaian kp ON kp.id=nk.komponen_id WHERE kp.pengajaran_id=? AND nk.siswa_id=?');$stmt->execute([$pid,$sid]);$manual=[];foreach($stmt->fetchAll() as $n)$manual[$n['komponen_id']]=$n['nilai'];
$stmt=$db->prepare('SELECT catatan FROM catatan_siswa_pengajaran WHERE pengajaran_id=? AND siswa_id=?');$stmt->execute([$pid,$sid]);$note=$stmt->fetchColumn();
$stmt=$db->prepare('SELECT rn.nilai_lama,rn.nilai_baru,rn.diubah_pada,kp.nama_komponen FROM riwayat_nilai rn JOIN komponen_penilaian kp ON kp.id=rn.komponen_id WHERE rn.pengajaran_id=? AND rn.siswa_id=? ORDER BY rn.diubah_pada DESC LIMIT 20');$stmt->execute([$pid,$sid]);$history=$stmt->fetchAll();
$map=['Ulangan Harian'=>'nilai_ulangan','Tugas Harian'=>'nilai_tugas','Kehadiran'=>'nilai_kehadiran'];$final=0;
?>
<style>@media print{#sidebar-wrapper,.no-print{display:none!important}#page-content-wrapper{margin:0!important;width:100%!important}.card{box-shadow:none!important}}.report{max-width:850px;margin:auto}.report-card{border:0;border-radius:16px;box-shadow:0 5px 20px #0001}</style>
<?php require_once __DIR__.'/../includes/sidebar.php'; ?><div id="page-content-wrapper"><main class="report p-3 p-md-4"><div class="d-flex justify-content-between mb-3 no-print"><a class="btn btn-light" href="rekap_nilai.php?pengajaran_id=<?= $pid ?>">Kembali</a><button class="btn btn-primary" onclick="window.print()"><i class="fa-solid fa-print me-1"></i>Cetak</button></div><section class="card report-card"><div class="card-body p-4"><div class="text-center border-bottom pb-3 mb-3"><h4 class="fw-bold">Laporan Nilai Siswa</h4><div><?= sanitize($info['nama_mapel'].' — '.$info['nama_kelas']) ?></div><small>Semester <?= sanitize($info['semester'].' · '.$info['tahun_ajaran']) ?></small></div><div class="row mb-3"><div class="col-7"><strong><?= sanitize($info['nama_lengkap']) ?></strong><br><small>NISN <?= sanitize($info['nisn']) ?></small></div><div class="col-5 text-end">KKM <strong><?= number_format($info['kkm'],2) ?></strong><br><small>Guru: <?= sanitize($info['nama_guru']) ?></small></div></div><table class="table table-bordered"><thead class="table-light"><tr><th>Komponen</th><th>Bobot</th><th>Nilai</th><th>Kontribusi</th></tr></thead><tbody><?php foreach($components as $c): $v=isset($map[$c['nama_komponen']])?(float)$auto[$map[$c['nama_komponen']]]:(float)($manual[$c['id']]??0);$part=$v*$c['bobot']/100;$final+=$part; ?><tr><td><?= sanitize($c['nama_komponen']) ?></td><td><?= number_format($c['bobot'],2) ?>%</td><td><?= number_format($v,2) ?></td><td><?= number_format($part,2) ?></td></tr><?php endforeach ?></tbody><tfoot><tr class="fw-bold"><td colspan="3">Nilai Akhir</td><td><?= number_format($final,2) ?></td></tr></tfoot></table><div class="alert <?= $final>=$info['kkm']?'alert-success':'alert-danger' ?>"><strong>Status: <?= $final>=$info['kkm']?'Tuntas':'Perlu Remedial' ?></strong></div><h6 class="fw-bold">Catatan Guru</h6><p class="border rounded p-3"><?= $note?nl2br(sanitize($note)):'<span class="text-muted">Belum ada catatan.</span>' ?></p><?php if($history): ?><h6 class="fw-bold mt-4 no-print">Riwayat Perubahan Nilai</h6><div class="table-responsive no-print"><table class="table table-sm"><thead><tr><th>Waktu</th><th>Komponen</th><th>Perubahan</th></tr></thead><tbody><?php foreach($history as $h): ?><tr><td><?= date('d/m/Y H:i',strtotime($h['diubah_pada'])) ?></td><td><?= sanitize($h['nama_komponen']) ?></td><td><?= $h['nilai_lama']===null?'Belum ada':number_format($h['nilai_lama'],2) ?> → <?= number_format($h['nilai_baru'],2) ?></td></tr><?php endforeach ?></tbody></table></div><?php endif ?></div></section></main></div><?php require_once __DIR__.'/../includes/footer.php'; ?>
