<?php
require_once __DIR__.'/../includes/header.php';
require_once __DIR__.'/../config/database.php';
check_access([2]);$db=Database::getInstance();
$stmt=$db->prepare("SELECT u.id,u.nama_ujian,u.jenis_ujian,p.kelas_id,p.mapel_id,k.nama_kelas,m.nama_mapel
 FROM ujian u JOIN pengajaran p ON p.id=u.pengajaran_id JOIN guru g ON g.id=p.guru_id
 JOIN kelas k ON k.id=p.kelas_id JOIN mapel m ON m.id=p.mapel_id WHERE g.user_id=?
 ORDER BY k.nama_kelas,m.nama_mapel,u.nama_ujian");$stmt->execute([$_SESSION['user_id']]);$opsiUjian=$stmt->fetchAll();
$ujianId=(int)($_GET['ujian_id']??0);$sesiId=(int)($_GET['sesi_id']??0);$filterKelas=(int)($_GET['kelas_id']??0);$filterMapel=(int)($_GET['mapel_id']??0);
if($ujianId>0){foreach($opsiUjian as $o)if((int)$o['id']===$ujianId){if(!$filterKelas)$filterKelas=(int)$o['kelas_id'];if(!$filterMapel)$filterMapel=(int)$o['mapel_id'];break;}}
if(!$filterKelas&&$opsiUjian)$filterKelas=(int)$opsiUjian[0]['kelas_id'];
$mapelTersedia=array_values(array_filter($opsiUjian,static fn($o)=>(int)$o['kelas_id']===$filterKelas));
if(!$filterMapel&&$mapelTersedia)$filterMapel=(int)$mapelTersedia[0]['mapel_id'];
$ujianTersedia=array_values(array_filter($opsiUjian,static fn($o)=>(int)$o['kelas_id']===$filterKelas&&(int)$o['mapel_id']===$filterMapel));
if(!$ujianId||!array_filter($ujianTersedia,static fn($o)=>(int)$o['id']===$ujianId))$ujianId=(int)($ujianTersedia[0]['id']??0);
$stmt=$db->prepare("SELECT u.id,u.nama_ujian,u.jenis_ujian,u.durasi_menit,m.nama_mapel,k.nama_kelas,g.nama_lengkap nama_guru
 FROM ujian u JOIN pengajaran p ON p.id=u.pengajaran_id JOIN guru g ON g.id=p.guru_id
 JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id
 WHERE u.id=? AND g.user_id=?");$stmt->execute([$ujianId,$_SESSION['user_id']]);$ujian=$stmt->fetch();
if(!$ujian){http_response_code(404);exit('Belum ada ujian pada kelas atau mata pelajaran ini.');}
$stmt=$db->prepare("SELECT su.id,su.waktu_mulai,su.waktu_selesai,su.status,s.id siswa_id,s.nisn,s.nama_lengkap,
 SUM(CASE WHEN js.id IS NOT NULL AND ((js.jawaban_pg IS NOT NULL) OR (js.jawaban_esai IS NOT NULL AND TRIM(js.jawaban_esai)<>'')) THEN 1 ELSE 0 END) jumlah_dijawab,(SELECT COUNT(*) FROM soal_ujian so WHERE so.ujian_id=su.ujian_id) total_soal,
 COALESCE(nu.nilai_pg,0) nilai_pg,COALESCE(nu.nilai_esai,0) nilai_esai,COALESCE(nu.nilai_total,0) nilai_total
 FROM sesi_ujian su JOIN siswa s ON s.id=su.siswa_id
 LEFT JOIN jawaban_siswa js ON js.sesi_ujian_id=su.id
 LEFT JOIN nilai_ujian nu ON nu.ujian_id=su.ujian_id AND nu.siswa_id=su.siswa_id
 WHERE su.ujian_id=? GROUP BY su.id ORDER BY su.status='Berlangsung' DESC,s.nama_lengkap");$stmt->execute([$ujianId]);$peserta=$stmt->fetchAll();
$detail=null;$jawaban=[];
if($sesiId>0){
 $stmt=$db->prepare("SELECT su.id,su.status,su.waktu_mulai,su.waktu_selesai,s.nisn,s.nama_lengkap
  FROM sesi_ujian su JOIN siswa s ON s.id=su.siswa_id WHERE su.id=? AND su.ujian_id=?");$stmt->execute([$sesiId,$ujianId]);$detail=$stmt->fetch();
 if(!$detail){http_response_code(404);exit('Sesi siswa tidak ditemukan.');}
 $stmt=$db->prepare("SELECT so.id,so.tipe_soal,so.pertanyaan,so.opsi_a,so.opsi_b,so.opsi_c,so.opsi_d,so.opsi_e,so.kunci_jawaban,so.bobot,
  js.jawaban_pg,js.jawaban_esai,js.is_benar,js.nilai_esai
  FROM soal_ujian so LEFT JOIN jawaban_siswa js ON js.soal_id=so.id AND js.sesi_ujian_id=?
  WHERE so.ujian_id=? ORDER BY so.id");$stmt->execute([$sesiId,$ujianId]);$jawaban=$stmt->fetchAll();
}
$selesai=count(array_filter($peserta,static fn($p)=>$p['status']==='Selesai'));$berlangsung=count($peserta)-$selesai;
?>
<?php require_once __DIR__.'/../includes/sidebar.php'; ?>
<style>
.result-page{background:#f5f7fb;min-width:0}.result-main{width:100%;padding:24px 28px}.result-card{border:1px solid #e7ecf3;border-radius:18px;box-shadow:0 6px 22px rgba(15,23,42,.05)}.result-hero{border:0;border-radius:20px;color:#fff;background:linear-gradient(125deg,#172554,#2563eb);box-shadow:0 10px 28px rgba(37,99,235,.2)}.result-metric{min-width:110px;padding:11px 15px;border-radius:13px;background:rgba(255,255,255,.12);text-align:center}.result-metric strong{display:block;font-size:1.25rem}.result-metric small{font-size:.68rem;opacity:.8}.answer-card{border:1px solid #e5eaf2;border-radius:15px;padding:18px;background:#fff}.answer-card+.answer-card{margin-top:12px}.answer-question{line-height:1.65;color:#1e293b}.answer-box{padding:11px 13px;border-radius:10px;background:#f8fafc}.answer-correct{border-left:4px solid #22c55e}.answer-wrong{border-left:4px solid #ef4444}.answer-empty{border-left:4px solid #94a3b8}.participant-mobile{display:none}.score-badge{min-width:58px;font-size:.85rem}.result-table th{white-space:nowrap;font-size:.72rem;text-transform:uppercase;color:#64748b}.result-table td{vertical-align:middle}@media(max-width:767.98px){.result-main{padding:13px}.result-hero{border-radius:16px}.result-hero .card-body{padding:18px!important}.result-metrics{width:100%;display:grid!important;grid-template-columns:repeat(3,1fr)}.result-metric{min-width:0;padding:9px 5px}.result-desktop{display:none}.participant-mobile{display:block}.participant-item{padding:14px;border:1px solid #e5eaf2;border-radius:14px;background:#fff}.participant-item+.participant-item{margin-top:10px}.answer-card{padding:14px}.result-card{border-radius:15px}}
</style>
<div id="page-content-wrapper" class="result-page"><nav class="navbar top-navbar px-3 px-md-4 py-3"><div class="d-flex align-items-center gap-2"><a href="ujian.php" class="btn btn-sm btn-outline-secondary"><i class="fa-solid fa-arrow-left"></i></a><div><h5 class="fw-bold mb-0">Hasil & Jawaban Ujian</h5><small class="text-muted">Jawaban siswa masuk otomatis dari CBT</small></div></div></nav>
<main class="result-main">
<section class="card result-card mb-3"><div class="card-body p-3"><form method="get" id="resultFilterForm" class="row g-2 align-items-end"><div class="col-md-3"><label class="form-label small fw-semibold">Kelas</label><select class="form-select" name="kelas_id" id="hasilKelas"><?php $kelasSeen=[];foreach($opsiUjian as $o):if(isset($kelasSeen[$o['kelas_id']]))continue;$kelasSeen[$o['kelas_id']]=true; ?><option value="<?= (int)$o['kelas_id'] ?>" <?= $filterKelas===(int)$o['kelas_id']?'selected':'' ?>><?= sanitize($o['nama_kelas']) ?></option><?php endforeach ?></select></div><div class="col-md-3"><label class="form-label small fw-semibold">Mata Pelajaran</label><select class="form-select" name="mapel_id" id="hasilMapel"><?php $mapelSeen=[];foreach($mapelTersedia as $o):if(isset($mapelSeen[$o['mapel_id']]))continue;$mapelSeen[$o['mapel_id']]=true; ?><option value="<?= (int)$o['mapel_id'] ?>" <?= $filterMapel===(int)$o['mapel_id']?'selected':'' ?>><?= sanitize($o['nama_mapel']) ?></option><?php endforeach ?></select></div><div class="col-md-4"><label class="form-label small fw-semibold">Ujian / Kuis</label><select class="form-select" name="ujian_id" id="hasilUjian"><?php foreach($ujianTersedia as $o): ?><option value="<?= (int)$o['id'] ?>" <?= $ujianId===(int)$o['id']?'selected':'' ?>><?= sanitize($o['nama_ujian'].' ('.$o['jenis_ujian'].')') ?></option><?php endforeach ?></select></div><div class="col-md-2"><button class="btn btn-primary w-100"><i class="fa-solid fa-filter me-1"></i>Tampilkan</button></div></form></div></section>
<section class="card result-hero mb-3"><div class="card-body p-4 d-flex flex-wrap justify-content-between align-items-center gap-3"><div><span class="badge bg-light text-primary mb-2"><?= sanitize($ujian['jenis_ujian']) ?></span><h1 class="h4 fw-bold mb-1"><?= sanitize($ujian['nama_ujian']) ?></h1><p class="mb-0 opacity-75"><?= sanitize($ujian['nama_mapel'].' · '.$ujian['nama_kelas']) ?></p></div><div class="d-flex gap-2 result-metrics"><div class="result-metric"><strong><?= count($peserta) ?></strong><small>Peserta</small></div><div class="result-metric"><strong><?= $selesai ?></strong><small>Selesai</small></div><div class="result-metric"><strong><?= $berlangsung ?></strong><small>Berlangsung</small></div></div></div></section>
<?php if($detail): ?><section class="card result-card mb-3"><div class="card-body p-3 p-md-4"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><a class="small text-decoration-none" href="?ujian_id=<?= $ujianId ?>"><i class="fa-solid fa-arrow-left me-1"></i>Kembali ke peserta</a><h2 class="h5 fw-bold mt-2 mb-1"><?= sanitize($detail['nama_lengkap']) ?></h2><small class="text-muted">NISN <?= sanitize($detail['nisn']) ?> · <?= count($jawaban) ?> soal</small></div><span class="badge <?= $detail['status']==='Selesai'?'bg-success':'bg-warning text-dark' ?>"><?= sanitize($detail['status']) ?></span></div>
<?php foreach($jawaban as $i=>$j): $kosong=$j['tipe_soal']==='PG'?$j['jawaban_pg']===null:trim((string)$j['jawaban_esai'])==='';$benar=$j['tipe_soal']==='PG'&&!$kosong&&(int)$j['is_benar']===1; ?><article class="answer-card"><div class="d-flex justify-content-between gap-2 mb-2"><span class="badge bg-primary">Soal <?= $i+1 ?> · <?= sanitize($j['tipe_soal']) ?></span><small class="text-muted">Bobot <?= (int)$j['bobot'] ?></small></div><div class="answer-question mb-3"><?= nl2br(sanitize($j['pertanyaan'])) ?></div>
<?php if($j['tipe_soal']==='PG'): ?><div class="answer-box <?= $kosong?'answer-empty':($benar?'answer-correct':'answer-wrong') ?>"><div class="d-flex flex-wrap justify-content-between gap-2"><span>Jawaban siswa: <strong><?= $kosong?'Belum dijawab':sanitize($j['jawaban_pg']) ?></strong></span><span>Kunci: <strong class="text-success"><?= sanitize($j['kunci_jawaban']) ?></strong></span></div><?php if(!$kosong): ?><small class="<?= $benar?'text-success':'text-danger' ?>"><i class="fa-solid <?= $benar?'fa-circle-check':'fa-circle-xmark' ?> me-1"></i><?= $benar?'Jawaban benar':'Jawaban salah' ?></small><?php endif ?></div>
<?php else: ?><div class="answer-box <?= $kosong?'answer-empty':'answer-correct' ?>"><strong class="d-block small text-muted mb-1">Jawaban esai siswa</strong><?= $kosong?'<span class="text-muted">Belum dijawab</span>':nl2br(sanitize($j['jawaban_esai'])) ?></div><?php endif ?></article><?php endforeach ?>
</div></section>
<?php else: ?><section class="card result-card"><div class="card-body p-3 p-md-4"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h2 class="h6 fw-bold mb-1">Daftar Peserta</h2><small class="text-muted">Klik detail untuk melihat setiap jawaban siswa</small></div><div class="d-flex gap-2"><a class="btn btn-sm btn-success" href="ujian_hasil_export.php?format=excel&amp;ujian_id=<?= $ujianId ?>"><i class="fa-solid fa-file-excel me-1"></i>Excel Kelas</a><a class="btn btn-sm btn-danger" href="ujian_hasil_export.php?format=pdf&amp;ujian_id=<?= $ujianId ?>"><i class="fa-solid fa-file-pdf me-1"></i>PDF Kelas</a></div></div>
<?php if(!$peserta): ?><div class="text-center py-5"><i class="fa-solid fa-inbox fa-2x text-muted mb-2"></i><p class="text-muted mb-0">Belum ada siswa yang memulai ujian.</p></div><?php else: ?>
<div class="table-responsive result-desktop"><table class="table table-hover result-table mb-0"><thead class="table-light"><tr><th>Siswa</th><th>Status</th><th>Jawaban</th><th>Waktu</th><th>Nilai Otomatis</th><th>Aksi</th></tr></thead><tbody><?php foreach($peserta as $p): ?><tr><td><strong><?= sanitize($p['nama_lengkap']) ?></strong><br><small class="text-muted"><?= sanitize($p['nisn']) ?></small></td><td><span class="badge <?= $p['status']==='Selesai'?'bg-success':'bg-warning text-dark' ?>"><?= sanitize($p['status']) ?></span></td><td><?= (int)$p['jumlah_dijawab'] ?> / <?= (int)$p['total_soal'] ?></td><td><small>Mulai: <?= date('d/m/Y H:i',strtotime($p['waktu_mulai'])) ?><br>Selesai: <?= $p['waktu_selesai']?date('d/m/Y H:i',strtotime($p['waktu_selesai'])):'-' ?></small></td><td><span class="badge bg-primary score-badge"><?= number_format($p['nilai_total'],2) ?></span></td><td><div class="d-flex gap-1"><a class="btn btn-sm btn-outline-primary" href="?ujian_id=<?= $ujianId ?>&amp;sesi_id=<?= (int)$p['id'] ?>"><i class="fa-solid fa-eye"></i></a><a title="Excel siswa" class="btn btn-sm btn-outline-success" href="ujian_hasil_export.php?format=excel&amp;ujian_id=<?= $ujianId ?>&amp;siswa_id=<?= (int)$p['siswa_id'] ?>"><i class="fa-solid fa-file-excel"></i></a><a title="PDF siswa" class="btn btn-sm btn-outline-danger" href="ujian_hasil_export.php?format=pdf&amp;ujian_id=<?= $ujianId ?>&amp;siswa_id=<?= (int)$p['siswa_id'] ?>"><i class="fa-solid fa-file-pdf"></i></a></div></td></tr><?php endforeach ?></tbody></table></div>
<div class="participant-mobile"><?php foreach($peserta as $p): ?><article class="participant-item"><div class="d-flex justify-content-between align-items-start gap-2"><div><strong><?= sanitize($p['nama_lengkap']) ?></strong><small class="text-muted d-block">NISN <?= sanitize($p['nisn']) ?></small></div><span class="badge <?= $p['status']==='Selesai'?'bg-success':'bg-warning text-dark' ?>"><?= sanitize($p['status']) ?></span></div><div class="d-flex justify-content-between align-items-end mt-3"><div><small class="text-muted d-block">Jawaban <?= (int)$p['jumlah_dijawab'] ?>/<?= (int)$p['total_soal'] ?></small><strong class="text-primary">Nilai <?= number_format($p['nilai_total'],2) ?></strong></div><div class="d-flex gap-1"><a class="btn btn-sm btn-outline-primary" href="?ujian_id=<?= $ujianId ?>&amp;sesi_id=<?= (int)$p['id'] ?>"><i class="fa-solid fa-eye"></i></a><a class="btn btn-sm btn-outline-success" href="ujian_hasil_export.php?format=excel&amp;ujian_id=<?= $ujianId ?>&amp;siswa_id=<?= (int)$p['siswa_id'] ?>"><i class="fa-solid fa-file-excel"></i></a><a class="btn btn-sm btn-outline-danger" href="ujian_hasil_export.php?format=pdf&amp;ujian_id=<?= $ujianId ?>&amp;siswa_id=<?= (int)$p['siswa_id'] ?>"><i class="fa-solid fa-file-pdf"></i></a></div></div></article><?php endforeach ?></div>
<?php endif ?></div></section><?php endif ?>
</main></div>
<script>document.getElementById('hasilKelas')?.addEventListener('change',function(){document.getElementById('hasilMapel').disabled=true;document.getElementById('hasilUjian').disabled=true;document.getElementById('resultFilterForm').submit()});document.getElementById('hasilMapel')?.addEventListener('change',function(){document.getElementById('hasilUjian').disabled=true;document.getElementById('resultFilterForm').submit()});</script>
<?php require_once __DIR__.'/../includes/footer.php'; ?>
